In [1]:
#import numpy library
import numpy as np

In [2]:
#dir (np)

In [3]:
x = np.array([40,50,60,70,80])
print(x)
print(type(x))
print(x.dtype)

[40 50 60 70 80]
<class 'numpy.ndarray'>
int32


In [4]:
x = np.array([40,50,60,7.8,80])
print(x)
print(type(x))
print(x.dtype)

[40.  50.  60.   7.8 80. ]
<class 'numpy.ndarray'>
float64


In [6]:
x = np.array(['A',50,60,7.6,80])
print(x)
print(type(x))
print(x.dtype)

['A' '50' '60' '7.6' '80']
<class 'numpy.ndarray'>
<U32


In [8]:
a2 = np.array([[20,30,40],[50,60,70]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2.dtype)

[[20 30 40]
 [50 60 70]]
<class 'numpy.ndarray'>
(2, 3)
int32


In [22]:
a = np.array([10,20,30,40,60,70])
b = a.reshape(2,3)
print(b) 
print(b.shape)

[[10 20 30]
 [40 60 70]]
(2, 3)


In [17]:
#create an array with arange()
c = np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [23]:
# use of around()
d = np.array([1.2367,2.23,3.23])           #taking approximate number
print(d)
np.around(d,2)

[1.2367 2.23   3.23  ]


array([1.24, 2.23, 3.23])

In [24]:
#Use of n.sqrt()
d = np.array([1.234, 2.234, 3.234])
print(d)
print(np.around(np.sqrt(d),2))

[1.234 2.234 3.234]
[1.11 1.49 1.8 ]


# 2D array

In [27]:
a1 = np.array([[3,4,5,6],[7,8,9,np.NAN]])
print(a1)
print(a1.shape)
print(a1.dtype)

[[ 3.  4.  5.  6.]
 [ 7.  8.  9. nan]]
(2, 4)
float64


In [30]:
#Use of astype() to convert the datatype
a1_copy = a1.astype(str)
print(a1_copy)
a1_copy.dtype

[['3.0' '4.0' '5.0' '6.0']
 ['7.0' '8.0' '9.0' 'nan']]


dtype('<U32')

In [31]:
a2 = np.array([[2,3,4],[5,6,7],[8,9,10]])
a2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [33]:
a2 = np.array([[2,3,4],[5,6,7],[8,9,10]])
a2
print(a2.sum(axis=1))
print(a2.sum(axis=0))

[ 9 18 27]
[15 18 21]


In [36]:
print(a2)
print(a2.mean(axis=0))
print(a2.mean(axis=1))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[5. 6. 7.]
[3. 6. 9.]


# Matrix operations

In [39]:
a3 = np.array([[3,4,5],[3,6,8],[9,2,8]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [3 6 8]
 [9 2 8]]
[[0 4 5]
 [3 0 8]
 [9 2 0]]


In [41]:
#Define two matrices and multiply them
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = np.matmul(A, B)
print(A)
print(B)
print(A.T)
print(B.T)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [42]:
#access the array elements
a4 = np.array([[3,4,5],[7,2,3],[9,1,3],[4,7,0]])
a4

array([[3, 4, 5],
       [7, 2, 3],
       [9, 1, 3],
       [4, 7, 0]])

In [43]:
a4[1][1]

2

In [45]:
a4[3][2]

0

In [47]:
#Slicing
a4[1:3,0:2]   # row,col

array([[7, 2],
       [9, 1]])